repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.6
    hooks:
    -   id: autopep8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      language_version: python3.9