name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        include:
          - os: ubuntu-20.04
            friendlyName: Ubuntu
            path: ~/.cache/pip
          - os: macos-latest
            friendlyName: macOS
            path: ~/Library/Caches/pip
          - os: windows-latest
            friendlyName: Windows
            path: ~\AppData\Local\pip\Cache

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1

    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      run: |
        python -m unittest discover -v -s "./tests/" -p "*_test.py"

  flake8_py3:
    name: Lint
    if: always()
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.2
          architecture: x64

      - uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Slack Notification
    if: always()
    runs-on: ubuntu-latest
    needs: [flake8_py3]

    steps:
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-alert
        SLACK_COLOR: "${{ needs.build.result == 'success' && '#00ff00' || '#ff0000' }}"
        SLACK_ICON: https://raw.githubusercontent.com/MercurySeven/project-docs/main/Stile/Logo_blank.png
        SLACK_TITLE: "La build è ${{ needs.build.result == 'success' && 'valida' || 'fallita' }}"
        SLACK_USERNAME: Huston - Bot
        MSG_MINIMAL: Commit,Actions URL
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
