name: CI

on: [push]

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            friendlyName: Ubuntu
            path: ~/.cache/pip
          - os: macos-latest
            friendlyName: macOS
            path: ~/Library/Caches/pip
          - os: windows-latest
            friendlyName: Windows
            path: ~\AppData\Local\pip\Cache

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4

    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - if: runner.os != 'Linux'
      name: Test All
      run: |
        python -m unittest discover -v -s "./tests/" -p "*_test.py"

    - if: runner.os == 'Linux'
      name: Unit Test
      run: |
        python -m unittest discover -v -s "./tests/model/" -p "*_test.py"
        python -m unittest discover -v -s "./tests/" -p "settings_test.py"

  notify:
    name: Slack Notification
    if: always()
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-alert
        SLACK_COLOR: "${{ needs.build.result == 'success' && '#00ff00' || '#ff0000' }}"
        SLACK_ICON: https://raw.githubusercontent.com/MercurySeven/project-docs/main/Stile/Logo_blank.png
        SLACK_TITLE: "La build è ${{ needs.build.result == 'success' && 'valida' || 'fallita' }}"
        SLACK_USERNAME: Huston - Bot
        MSG_MINIMAL: Commit,Actions URL
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
