on: [push]
name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: linux-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          linux-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      run: |
        coverage run -m unittest discover -p "*_test.py"
        coverage xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.python.coverage.reportPaths=coverage.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 